=== devajdev/Webservices/Jax-p_StaXParserValidate-XSD-XML/bank.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Bnak" type="BankType"/>
		<xs:complexType name="BankType">
			<xs:sequence>
				<xs:element name="account" type="accountType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:complexType name="accountType">
			<xs:sequence>
				<xs:element name="id" type="xs:int"/>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="amt" type="xs:double"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string"/>
		</xs:complexType>
</xs:schema>

=== devajdev/Webservices/XML/account.xml
<?xml version="1.0" encoding="UTF-8"?>
<Bnak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Java%20Package/WebServices/XSD/bank.xsd">
	<account type="saving">
		<id>100</id>
		<name>Devaj</name>
		<amt>5000</amt>
	</account>
	<account type="current">
		<id>500</id>
		<name>Dev</name>
		<amt>10000</amt>
	</account>
</Bnak>
