=== devajdev/Webservices/DTD/book-store.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT author (name, email)>
<!ELEMENT book (name, price, quantity)>
<!ELEMENT books (book)>
<!ELEMENT bookStore (books,author)>

=== devajdev/Webservices/XML/book-store.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookStore SYSTEM "D:\Java Package\WebServices\DTD\book-store.dtd">
<bookStore>
	<books>
		<book>
			<name>Spring</name>
			<price>500</price>
			<quantity>5</quantity>
		</book>
	</books>
	<author>
		<name>Devaj</name>
		<email>devaj04@gmail.com</email>
	</author>
</bookStore>
