=== devajdev/Webservices/XSD/bank-group-sequence.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:group name="accountDetails">
		<xs:sequence>
			<xs:element name="acc-no" type="xs:int"/>
			<xs:element name="holder-name" type="xs:string"/>
			<xs:element name="branch-name" type="xs:string"/>
		</xs:sequence>
	</xs:group>
	
		<xs:element name="bankaccount" type="bankaccountType"/>
		
			<xs:complexType name="bankaccountType">
				<xs:sequence>
					<xs:element name="saving-account" type="saving-accountType"/>
					<xs:element name="current-account" type="current-accountType"/>
				</xs:sequence>				
			</xs:complexType>
			
			<xs:complexType name="saving-accountType">
				<xs:sequence>
					<xs:group ref="accountDetails"/>
					<xs:element name="min-bal" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
		
			<xs:complexType name="current-accountType">
				<xs:sequence>
					<xs:group ref="accountDetails"/>
					<xs:element name="tx-limit" type="xs:int"/>
				</xs:sequence>
			</xs:complexType>
			
</xs:schema>

=== devajdev/Webservices/XML/bank.xml
<?xml version="1.0" encoding="UTF-8"?>
<bankaccount xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Java%20Package/WebServices/XSD/bank-group-sequence.xsd">
	<saving-account>
		<acc-no>1000</acc-no>
		<holder-name>Devaj</holder-name>
		<branch-name>Ameerpet</branch-name>
		<min-bal>150000</min-bal>
	</saving-account>
	<current-account>
		<acc-no>5000</acc-no>
		<holder-name>Raja</holder-name>
		<branch-name>S R Nagar</branch-name>
		<tx-limit>10000</tx-limit>
	</current-account>
</bankaccount>
